# -*- coding: utf-8 -*-
"""array_inspection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tALuCCULqAUxrUsaKFfTMuYb4XKX7PtZ

Write a Python program to create a NumPy array from a list and print its shape.
List = [1, 2, 3, 4, 5, 6]
"""

l =[1, 2, 3, 4, 5, 6]
import numpy as np
a = np.asarray(l)
print(a)
print('-'*20)
a.shape

"""Write a Python program to create a NumPy array and print its number of dimensions (ndim).
Array = [[1,2,3],[4,5,6]]
"""

b = np.array([[1,2,3],[4,5,6]])
print(b)
print("-"*20)
b.ndim

"""Write a Python program to create a NumPy array and print its total number of elements (size).
Array = [10, 20, 30, 40, 50]

"""

c= np.array([10,20,30,40,50])
print(c)
print("-"*20)
c.size

"""Write a Python program to find the data type (dtype) of a given NumPy array.
Array = [1.0, 2.5, 3.8]
"""

d = np.array([1.0,2.5,3.8])
d.dtype

"""
Write a Python program to convert the data type of a NumPy array from float to int using astype().
Array = [5.5, 6.7, 8.9]"""

e = np.array([5.5, 6.7, 8.9])
e.dtype
ee= e.astype(int)
ee.dtype