# -*- coding: utf-8 -*-
"""Indexing_Slicing_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swGz8pYgD75muHaUjwoQDNwcn1g2zM5h

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])
"""

# importing numpy libery
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a[0]

"""Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])
"""

b = np.array([1, 2, 3, 4, 5])
b[-3:]

"""Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
"""

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c[1,2]

"""Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
"""

d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d[0,:]

"""Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
"""

e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#e[:,2]
e[:,-1]

"""Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

f = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
f[1,2,2]

"""Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

g = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
#g[0,:,:]
g[0]

"""Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

h = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
h[-1]