# -*- coding: utf-8 -*-
"""array_manupulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoGQ2tgQ-jOlYybS8k5nAL6ZZaj45KEi

Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
"""

# importing numpy libery
import numpy as np
# creating array
a = np.array([[1, 2, 3], [4, 5, 6]])
# using transpose function for array manupulation
aa= np.transpose(a)
# checking shape of array
aa.shape

"""Write a Python program to create a NumPy array and print its number of dimensions (ndim).
Array = [[1,2,3],[4,5,6]]

"""

l = [[1,2,3],[4,5,6]]
# creating array
b = np.asarray(l)
b.ndim

"""Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])

Example Output:

Reshaped Array: [[1 2] [3 4] [5 6]]
"""

# creating array
a = np.array([1, 2, 3, 4, 5, 6])
# changing shape to
aa = np.reshape(a,(3,2))
aa.shape
print(aa)

"""Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8]) Example Output:

Resized Array: [[1 2 3] [4 5 6] [7 8 1]]
"""

import numpy as np
# creating new array
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# changing shape to 3*3
bb= np.resize(b,(3,3))
print(bb)

'''bb = b.resize((3,3))
print(bb)'''

bb.ndim

"""Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) Example Output:

Flattened Array: [1 2 3 4 5 6]
"""

# creating array
c =  np.array([[1, 2, 3], [4, 5, 6]])
cc= c.flatten()
cc.ndim

"""Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

Example Output:

Transposed Array: [[[ 1 5 9] [ 2 6 10]]

[[ 3 7 11] [ 4 8 12]]]
"""

d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

dd= d.transpose()
print(dd)
dd.ndim

"""Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:

Reshaped Array: [[ 1 2 3] [ 4 5 6] [ 7 8 9] [10 11 12]]
"""

f =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

ff = np.reshape(f,(4,3))
ff.ndim
print(ff)

"""Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:

arr_2d = np.array([[1, 2], [3, 4]])

Example Output:

Resized Array: [[1 2 1 2] [3 4 3 4] [1 2 1 2] [3 4 3 4]]
"""

g = np.array([[1, 2], [3, 4]])

gg = np.resize(g,(4,4))
print(gg)

"""Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:

Flattened Array: [1 2 3 4 5 6 7 8]
"""

h = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
h.ndim
hh = h.flatten()
print(hh)
hh.ndim