# -*- coding: utf-8 -*-
"""array_creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RK2oeXa-XJwbUyRHHXSvm2gpHBv8zrru
"""

b = np.array([1,2,3,4,7,9])
print(b)

c = np.array([[1,2,3],[4,5,6]])
print(c)
c.shape

d = np.array([ [[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]] ])
print(d)
d.shape

d.astype('float64')