# -*- coding: utf-8 -*-
"""for_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3n2ACu48sufdGv6YqYlIYoUqU2tGu3I

1.	Given a list [4, 8, 2, 10, 6], find the maximum number using a for loop.
"""

l = [4, 8, 2, 10, 6]
# using for loop
ans = 0
for i in l:
  if i > ans:
    ans = i
print(ans)

"""2.	Take input from the user and find the factorial of the number using a for loop.

"""

# accept input from user
num = int(input("Enter a Number = "))
facto = 1
for i in range(1,num+1):
  facto = facto *i
print(facto)

"""3.	Given a list ['apple', 'banana', 'cherry', 'date', 'fig'], print each element along with its index using a for loop.

"""

# list of fruit
fruits = ['apple', 'banana', 'cherry', 'date', 'fig']
# using emurate fuction for indexing
for index,i in enumerate(fruits):
  print(index, " = " ,i)

"""4.	Take a string input from the user and count the number of uppercase letters using a for loop. (Use char.isupper()) 😊

"""

# accept string from user
word = input("Enter a string = ")
count = 0
for i in word:
  if i.isupper():
    count = count + 1
print(count)

"""5.	Given a list of integers [17, 25, 39, 42, 58, 71, 86, 93], find the sum of all the even numbers using a for loop.

"""

l = [17, 25, 39, 42, 58, 71, 86, 93]
# empty variable
sum = 0
# for loop
for i in l:
  if i%2 == 0:
     sum = sum + i
print(sum)

"""6.	Given a list [3, 6, 9, 12, 15], calculate the product of all the elements using a for loop.

"""

# The given list
numbers = [3, 6, 9, 12, 15]

# Initializing the product variable to 1
product = 1

# Using a for loop to multiply each element
for num in numbers:
    product *= num  # This is the same as product = product * num

print(f"The product of all elements is: {product}")

"""7.	Given a list [2, 3, 5, 7, 11, 13, 17, 19], find the index of the first occurrence of the number 7 using a for loop.

"""

# The given list
numbers = [2, 3, 5, 7, 11, 13, 17, 19]

for index,i in enumerate(numbers):
  if i == 7:
    print("index of 7 is" " = ", index)

"""19.	Given a dictionary {'A': 10, 'B': 20, 'C': 30, 'D': 40}, print all key-value pairs using a for loop.

"""

dictt = {'A': 10, 'B': 20, 'C': 30, 'D': 40}

# Using a for loop with .items() to unpack keys and values
for key, value in dictt.items():
    print(key,"=",value)