# -*- coding: utf-8 -*-
"""if_elif_else_statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GS6vhucB6XrIxLxuKOQbme9WBYoSg9LY

#if-elif-else statements:

Question 1: Write a Python program that checks if a given number is positive, negative, or zero. Print the corresponding message.
"""

# Taking user input
number = float(input("Enter a number: "))

# Checking the number status
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

"""Question 2: Write a Python program that compares two numbers and prints the larger number."""

# Taking two numbers as input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Comparing the numbers
if num1 > num2:
    print(f"The larger number is {num1}.")
elif num2 > num1:
    print(f"The larger number is {num2}.")
else:
    print("Both numbers are equal.")

"""Question 3: Write a Python program that determines whether a given temperature is hot, warm, or cold. Print the corresponding message."""

# Taking temperature input
temp = float(input("Enter the temperature in Celsius: "))

# Categorizing the temperature
if temp >= 30:
    print("It is hot.")
elif temp >= 15 and temp <30:
    print("It is warm.")
else:
    print("It is cold.")

"""Question 4: Write a Python program that checks if a given year is a leap year, a century year, or neither. Print the corresponding message."""

# Taking year input
year = int(input("Enter a year: "))

# Logic to check the type of year
if year % 400 == 0:
    print(f"{year} is both a Century Year and a Leap Year.")
elif year % 100 == 0:
    print(f"{year} is a Century Year but not a Leap Year.")
elif year % 4 == 0:
    print(f"{year} is a Leap Year.")
else:
    print(f"{year} is neither a Leap Year nor a Century Year.")

"""Question 5: Write a Python program that categorizes a given character into uppercase letter, lowercase letter, digit, or special character. Print the corresponding message."""

# Taking character input
char = input("Enter a single character: ")

# Ensuring the input is only one character
if len(char) != 1:
    print("Please enter exactly one character.")
else:
    # Categorizing the character
    if char.isupper():
        print(f"'{char}' is an uppercase letter.")
    elif char.islower():
        print(f"'{char}' is a lowercase letter.")
    elif char.isdigit():
        print(f"'{char}' is a digit.")
    else:
        print(f"'{char}' is a special character.")

"""Question 6: Write a Python program that calculates the discount percentage based on the purchase amount. Print the corresponding discount percentage."""

# Taking the purchase amount as input
amount = float(input("Enter the purchase amount: "))

# Determining the discount percentage
if amount >= 1000:
    print("You get a 20% discount.")
elif amount >= 500:
    print("you will get 15% discount")
elif amount >= 100:
    print("you will get 10% discount")
else:
    print("you will get 0% discount")