# -*- coding: utf-8 -*-
"""if_else_statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHZcjH2AfBGNO2WeMLGaUSbViF3jgww2

#IF Candition

Question 1: Write a Python program that checks if a given number is even. If it is, print "Even number".
"""

# accept input from user
num = int(input("Enter a Number = "))
# use module operator to find it is even number or odd number
if num%2 == 0:
  print(num, "is Even Number")
else:
  print(num, "is Odd Number")

"""Question 2: Write a Python program that checks if a given string contains the letter 'a'. If it does, print "String contains 'a'"."""

# accept string from user
abc = input("Enter a text = ")
abc = abc.lower()
if "a" in abc:
  print("String contains 'a'")
else:
  print("String does not contain 'a'")

"""Question 3: Write a Python program that checks if a given year is a leap year. If it is, print "Leap year"."""

# input year from user
year = int(input("enter year = "))
if year % 4 == 0:
  print(year, "is a leap year")
else:
  print(year, "is not a leap year")

"""Question 4: Write a Python program that checks if a given number is positive. If it is, print "Positive number"."""

# accept a number from user
num = int(input("Enter a Number "))
if num > 0:
  print(num, "is a Positive Number")

"""Question 5: Write a Python program that checks if a given character is a vowel. If it is, print "Vowel"."""

# create vowel list
vowel = ["a","e","i","o","u"]
# accept input from user
char = input("Enter a Character = ")
# if condition
if char in vowel:
  print(char, "is a vowel")

"""Question 6: Write a Python program that checks if a given number is greater than 100. If it is, print "Greater than 100"."""

# accept a number from use
num = int(input("enter a number = "))
if num > 100:
  print(num, "is greater than 100")

"""Question 7: Write a Python program that checks if a given number is divisible by both 5 and 7. If it is, print "Divisible by 5 and 7"."""

# accept a number from user
num = int(input("Enter a Number = "))
if num%5 == 0 and num%7 == 0:
  print(num, "is divisible by 5 and 7")

"""Question 8: Write a Python program that checks if a given list contains any negative numbers. If it does, print "List contains negative numbers"."""

l = [1,5,7,-4,-8]
for i in l:
  if i < 0:
    print("List contains negative numbers")
    break

"""Question 10: Write a Python program that checks if a given word is a palindrome. If it is, print "Palindrome"."""

word = input("Enter a word = ")
if word == word[::-1]:
  print(word," is a Palindrome")

"""#if-else statements:

Question 1: Write a Python program that checks if a given number is positive. If it is, print "Positive number"; otherwise, print "Negative number".
"""

# accept a number from user
num = int(input("Enter a Number = "))
if num > 0:
  print(num, "is a positive number")
elif num == 0:
  print(num, "is a neutal number")
else:
  print(num, "is a negative number")

"""Question 2: Write a Python program that checks if a given string is empty. If it is, print "Empty string"; otherwise, print "Non-empty string"."""

# accept a string from user
abc = input("Enter a text = ")
if abc == "":
  print("Empty String")
else:
  print("Non Empty String")

"""Question 3: Write a Python program that checks if a given number is even. If it is, print "Even number"; otherwise, print "Odd number"."""

# accept a number from user
num = int(input("enter a number = "))
if num%2 == 0:
  print(num, "is a even number")
else:
  print(num, "is odd number")

"""Question 4: Write a Python program that checks if a given character is a vowel. If it is, print "Vowel"; otherwise, print "Consonant"."""

# create vowel list
vowel = ["a","e","i","o","u"]
# accept charactor from user
char = input("Enter a Character = ")
if char in vowel:
  print(char, "is a vowel")
else:
  print(char, "is Consonant")

"""Question 5: Write a Python program that checks if a given year is a leap year. If it is, print "Leap year"; otherwise, print "Not a leap year"."""

# accept year from user
year = int(input("enter year = "))
if year%4 == 0:
  print("it is leap year")
else:
  print(" not leap year")

"""Question 7:Write a Python program that checks if a given character is an uppercase letter. If it is, print "Uppercase"; otherwise, print "Lowercase"."""

char = input("enter a character")
if char == char.upper():
  print("Uppercase")
else:
  print("Lowercase")

"""#if-elif-else statements:

Question 1: Write a Python program that checks if a given number is positive, negative, or zero. Print the corresponding message.
"""

