# -*- coding: utf-8 -*-
"""If_else_nested

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MK6Ed2byzu-iRx-fFOTBrueLtlbPz2I3

#Nested-if-else statements:

Question 1: Checking Number Properties
Write a Python program that takes an integer as input and checks the following conditions using nested if:
•	If the number is positive, check if it is even or odd.
•	If it is even, check if it is greater than 50.
•	If it is odd, check if it is a multiple of 5.
•	If the number is negative, print "Number is negative."
"""

# accept a integer as input from user
num = int(input("Enetr a Number"))
if num > 0:
  print(num, "is positive number")
  if num%2 ==0:
    print(num, "is even number")
    if num > 50:
      print(num, "is greater than 50")
  else:
    print(num, "is odd number")
    if num%5 ==0:
      print(num, "is a multiple of 5")
else:
  print("Number is negative")

"""Question 2: Student Grade Classification
Write a Python program that takes marks as input and classifies students based on the following criteria:
•	If the marks are 50 or above, print "You have passed."
o	If the marks are 75 or above, print "You got distinction!"
o	Else, print "You passed, but no distinction."
•	If marks are below 50, print "You have failed."

"""

# accept marks from student
marks = int(input("Enter your marks = "))
# if condition
if marks >=50:
  print("You have passed")
  if marks >=75:
    print("you got distinction")
  else:
    print("You passed, but no distinction")
else:
  print("You have failed")

"""Question 3: Checking Voter Eligibility
Write a Python program that takes the age of a person as input and checks if they are eligible for different activities:
•	If the age is 18 or above, print "Eligible to vote."
o	If the age is 21 or above, print "Eligible to drink alcohol."
o	Else, print "Not eligible to drink alcohol."
•	If the age is below 18, print "Not eligible to vote."
o	If the age is 16 or above, print "Can apply for a learner's driving permit."

"""

# takes age input from user
age = int(input("Enter your age = "))
# if statement
if age >= 18:
  print("Eligible to vote")
  if age >=21:
    print("Eligible to drink alcohol")
  else:
    print("Not eligible to drink alcohol")
else:
  print("Not Eligible to vote")
  if age >= 16:
    print('can apply for a learners driving permit')

"""Question 4: Employee Bonus Calculation
Write a Python program that takes an employee's salary and years of experience as input. The program should:
•	If the experience is 5 years or more, check:
o	If the salary is more than 50,000, give a bonus of 10%.
o	Else, give a bonus of 15%.
•	If the experience is less than 5 years, print "No bonus."

"""

# take salary input
salary = float(input("enter your salary = "))
# accept year of experiance
YOE = float(input("Enter your year of experience = "))
# conditional statement
if YOE >= 5:
  if salary > 50000:
    print("Bonus 10%")
  else:
    print("Bonus 15%")
else:
  print("NO Bonus, Experience less than 5 year")

"""Question 5: Triangle Type Checker
Write a Python program that takes three sides of a triangle as input and determines:
•	If all three sides are equal, print "Equilateral Triangle."
•	If any two sides are equal, print "Isosceles Triangle."
•	If all three sides are different, print "Scalene Triangle."
•	If the sum of any two sides is not greater than the third side, print "Not a valid triangle."

"""

# Taking input for the three sides
a = float(input("Enter side 1: "))
b = float(input("Enter side 2: "))
c = float(input("Enter side 3: "))

# 1. First check: Is it a valid triangle?
# The sum of any two sides must be greater than the third.
if (a + b <= c) or (a + c <= b) or (b + c <= a):
    print("Not a valid triangle.")

# 2. Check for Equilateral
elif a == b == c:
    print("Equilateral Triangle.")

# 3. Check for Isosceles
elif a == b or b == c or a == c:
    print("Isosceles Triangle.")

# 4. If none of the above, it must be Scalene
else:
    print("Scalene Triangle.")

"""Question 6: ATM Cash Withdrawal
Write a Python program that asks the user for the amount to withdraw. The program should check:
•	If the amount is a multiple of 100, proceed further.
o	If the amount is greater than 5000, print "Daily limit exceeded."
o	Else, print "Transaction successful."
•	If the amount is not a multiple of 100, print "Invalid amount. Enter multiples of 100."

"""

# Ask the user for the withdrawal amount
amount = int(input("Enter the amount to withdraw: "))

# Check if the amount is a multiple of 100
if amount % 100 == 0:
    # Check if the amount exceeds the daily limit
    if amount > 5000:
        print("Daily limit exceeded.")
    else:
        print("Transaction successful.")
else:
    # If the amount is not a multiple of 100
    print("Invalid amount. Enter multiples of 100.")