# -*- coding: utf-8 -*-
"""Introduction_to_Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjVsvyoyG5_jBZfFkM8eA0AzpvcN1wQC

Q1 Write a Python program that accepts a string from user. Your program should create and display a new string where the first and last characters have been exchanged.

For example if the user enters the string 'HELLO' then new string would be 'OELLH'
"""

# Code for 1st and last charactor exchange
name = input("Enter your name : ")
'''first_char = name[0]
mid_char = name[1:-1]  # -1 Cause end point work on n-1, so -1-1 = -2 which 2nd last char of name.
last_char = name[-1]
new_name = last_char+mid_char+first_char'''
word = name[-1]+name[1:-1]+name[0]
print(new_name)

"""Q2 Write a Python program that accepts a string from user. Your program should create a new string in reverse of first string and display it.

For example if the user enters the string 'EXAM' then new string would be 'MAXE'
"""

# program for reversing word/ string
word = input("Enter a word : ")
reverse_Word = word[::-1]
print(reverse_Word)

"""Q3 Write a Python program that accepts a string from user. Your program should create a new string by shifting one position to left.

For example if the user enters the string 'examination 2021' then new string would be 'xamination 2021e'
"""

#program for shifting one positoin to left
word = input("Enter a Word : ")
'''a = word[0]
b = word[1:]
new_word = b+a'''
# OR
new_word = word[1:]+word[0]
print(new_word)

"""Q4 Write a Python program to calculate the length of a string."""

# Program to calculate length of string
name = 'Shubham'
#name = input("Enter a Word : ")
len(name)
print(len(name))

"""Q5 Write a Python program to get a string made of the first 2 and last 2 characters of a given string. If the string length is less than 2, return the empty string instead.
Sample String : 'w3resource'
Expected Result : 'w3ce'
Sample String : 'w3'
Expected Result : 'w3w3'
Sample String : ' w'
Expected Result : Empty String
"""

# Code for word made up of 1st 2 charactor and last 2 charactor
word = input("Enter a word: ")
if len(word) < 2:
  print("Empty String")
else:
  new_word = word[0:2]+word[-2:]
  print(new_word)

"""Q6 Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string already ends with 'ing', add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged.
Sample String : 'abc'
Expected Result : 'abcing'
Sample String : 'string'
Expected Result : 'stringly'
"""

# code for adding ing in th last
word = input("Enter a word : ")
if len(word) < 3:
  print(word)
elif word[-3:] == "ing":
  word1 = word + 'ly'
  print(word1)
else:
  print(word+"ing")

"""Q7 Write a Python program to remove the nth index character from a nonempty string."""

# Removing nth number index
s = input("Enter a string : ")
n = int(input("Enter nth number to remove index number : "))
if len(s) > 0 and len(s)> n:
  first = s[:n]
  last = s[n+1:]
  print(first+last)
else:
 print("Invalid Input or Invalid Index number")

"""
Q8 Write a Python program to change a given string to a newly string where the first and last chars have been exchanged."""

# Replacing 1st and last char of string
word = input("Enter a word : ")
new_word = word[-1]+word[1:-1]+word[0]
print(new_word)

"""Q9 Write a Python script that takes input from the user and displays that in upper and lower cases."""

# Converting string in uppercase and lowercase
word  = input("Enter a word : ")
'''capitalword = word.upper()    # New variable to store
small_word = word.lower()
print(capitalword,"and", small_word)'''
# or
print(word.upper(), "and", word.lower())