# -*- coding: utf-8 -*-
"""List in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5RDw2xMXZlN47MEpzvIgeMQGtd0N6ed

1- Write a program to access the third element from the given list.
Input: [10, 20, 30, 40, 50]
"""

# extract 3rd element
l = [10,20,30,40,50]
l[2]

"""2 Write a program to access the last element from the given list using negative indexing.
Input: ['apple', 'banana', 'cherry', 'date']

"""

# extract last element by negative indexing

l= ['apple', 'banana', 'cherry', 'date']
l[-1]

"""3 Write a program to change the second element to 100 in the given list.
Input: [5, 10, 15, 20, 25]

"""

# Change 2nd element to 100
l=[5, 10, 15, 20, 25]
l[1]=100
print(l)

"""4 Write a program to access the first element using negative indexing.
Input: [7, 14, 21, 28, 35]

"""

# extract 1st element using negative indexing
l =  [7, 14, 21, 28, 35]
l[-5]

"""5 Write a program to access the second last element from the given list.
Input: [1, 2, 3, 4, 5, 6]

"""

# extract 2nd last element
l = [1, 2, 3, 4, 5, 6]
l[-2]

"""#**Slicing**

6 Write a program to extract the first three elements from the given list.
Input: [100, 200, 300, 400, 500, 600]
"""

# extract 1st 3 element
l = [100, 200, 300, 400, 500, 600]
l[:3]

"""7 Write a program to extract all elements except the first two from the given list.
Input: [2, 4, 6, 8, 10, 12]

"""

# extract all element except 1st two element
l =[2, 4, 6, 8, 10, 12]
l[2:]

"""8 Write a program to extract every alternate element from the given list.
Input: [5, 10, 15, 20, 25, 30, 35]

"""

# extract alterante element
l=[5, 10, 15, 20, 25, 30, 35]
l[::2]

"""9 Write a program to reverse the given list using slicing.
Input: [1, 3, 5, 7, 9]

"""

#reverse list using slicing
l= [1, 3, 5, 7, 9]
l[::-1]

"""10 Write a program to extract elements from index 2 to 5 from the given list.
Input: [11, 22, 33, 44, 55, 66, 77]

"""

# extract element from index 2 to 5
l=[11, 22, 33, 44, 55, 66, 77]
l[2:6]

"""#**Nested** **Slicing**

11 Write a program to access the second element from the first nested list.
Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
"""

# extract second element from 1st nested list
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l[0][1]

"""12 Write a program to extract the last element from the last nested list.
Input: [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]

"""

# extract last element from last nested list
l =[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
l[2][2]

"""13 Write a program to extract the second and third lists from a given nested list.
Input: [[10, 20], [30, 40], [50, 60], [70, 80]]

"""

# extract the second and third lists from a given nested list
l=[[10, 20], [30, 40], [50, 60], [70, 80]]
l[1:3]

"""14 Write a program to extract the second element from all nested lists.
Input: [[1, 9], [2, 8], [3, 7], [4, 6]]

"""

# get 2nd element form all nested list
l = [[1, 9], [2, 8], [3, 7], [4, 6]]
d = [x[1] for x in l]
print(d)

"""15 Write a program to reverse all sublists in a nested list.
Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

"""

# revesing sublist in nested list
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

d = [x[::-1] for x in l]
print(d)

"""#**Append**

1- Write a program to append the number 100 to the given list.
Input: [10, 20, 30, 40]
"""

# adding one element
l= [10, 20, 30, 40]
l.append(100)
print(l)

"""2 Write a program to append a string "Hello" to the given list.
Input: ['apple', 'banana', 'cherry']

"""

# add "hello" element
l =['apple', 'banana', 'cherry']
l.append("Hello")
print(l)

"""3 Write a program to append a list [5, 6, 7] as a single element in the given list.
Input: [1, 2, 3, 4]

"""

# add [5,6,7] as one element
l = [1, 2, 3, 4]
l.append([5,6,7])
print(l)

"""#extend

4 Write a program to extend the given list by adding another list [50, 60, 70].
Input: [10, 20, 30, 40]
"""

## Extend list by 50,60,70
l = [10, 20, 30, 40]
l.extend([50,60,70])
print(l)

"""5 Write a program to extend a list of numbers [7, 8, 9] with another list [10, 11, 12].
Input: [7, 8, 9]

"""

# Extend list by 10,11,12
l = [7, 8, 9]
l.extend([10,11,12])
print(l)

"""6 Write a program to extend a list of strings ["cat", "dog"] with another list ["lion", "tiger"]."""

# add list of string
l = ["cat", "dog"]
l.extend(["lion","tiger"])
print(l)

"""#pop function

7 Write a program to remove the last element from the given list using the pop function.
Input: [10, 20, 30, 40]
"""

#remove last element from list
l = [10, 20, 30, 40]
l.pop(-1)
print(l)

"""8 Write a program to remove the third element from the given list using the pop function.
Input: [1, 2, 3, 4, 5]

"""

# remove  3rd element frmo given list using pop function
l = [1, 2, 3, 4, 5]
l.pop(2)
l

"""9 Write a program to remove the first element from the given list using the pop function.
Input: [100, 200, 300, 400]

"""

# remove the first element from the given list using the pop function
l = [100, 200, 300, 400]
l.pop(0)
l

"""#Remove Function

10 Write a program to remove the element 20 from the given list.
Input: [10, 20, 30, 40, 50]
"""

# remove the element 20 from the given list
l = [10, 20, 30, 40, 50]
l.remove(20)
l

"""11 Write a program to remove the first occurrence of "apple" from the given list.
Input: ["banana", "apple", "cherry", "apple"]

"""

#remove the first occurrence of "apple" from the given list
l = ["banana", "apple", "cherry", "apple"]
l.remove("apple")
l

"""12 Write a program to remove the number 5 from the given list if it exists.
Input: [1, 2, 3, 4, 5, 6]

"""

# remove the number 5 from the given list if it exists
l = [1, 2, 3, 4, 5, 6]
l.remove(5)
l

"""#index() Function

13 Write a program to find the index of the element 50 in the given list.
Input: [10, 20, 30, 40, 50, 60]
"""

# find the index of the element 50 in the given list
l = [10, 20, 30, 40, 50, 60]
l.index(50)

"""14 Write a program to find the index of "cherry" in the given list.
Input: ["apple", "banana", "cherry", "date"]

"""

# find the index of "cherry" in the given list
l = ["apple", "banana", "cherry", "date"]
l.index("cherry")

"""15 Write a program to find the index of the number 100 in the given list. If not found, print "Not found"."""

# find the index of the number 100 in the given list
l = [10, 20, 30, 40]
if 100 in l:
  print(l.index(100))
else:
  print("not found")

"""#count() Function

16 Write a program to count the occurrences of 5 in the given list.
Input: [1, 5, 2, 5, 3, 5, 4]
"""

#  count the occurrences of 5 in the given list
l = [1, 5, 2, 5, 3, 5, 4]
l.count(5)

"""17 Write a program to count how many times "apple" appears in the given list.
Input: ["apple", "banana", "apple", "cherry", "apple"]

"""

# count how many times "apple" appears in the given list
l=["apple", "banana", "apple", "cherry", "apple"]
l.count("apple")

"""18 Write a program to count the occurrences of 100 in the given list.
Input: [10, 20, 30, 40, 50]

"""

#count the occurrences of 100 in the given list
l = [10, 20, 30, 40, 50]
l.count(100)

"""#min() and max() Function

19 Write a program to find the minimum value in the given list.
Input: [45, 12, 78, 34, 23]
"""

#find the minimum value in the given list
l=[45, 12, 78, 34, 23]
min(l)

"""20 Write a program to find the maximum value in the given list.
Input: [99, 55, 73, 21, 64]

"""

#find the maximum value in the given list. Input: [99, 55, 73, 21, 64]
l = [99, 55, 73, 21, 64]
max(l)