# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbpJk-Zajs0nOSWnGfJXbv4WgfzaTozN

1.	Write a Python program to take two numbers as input from the user and display their sum.
"""

# Addition of two numbers
num1 = int(input("Enter a Number "))
num2 = int(input("Enter 2nd Number "))
add = num1+num2
print("Addition of Two Number = ",add)

"""2.	Calculate and print the midpoint of two numbers entered by the user.

"""

# Calculate midpoint
num1 = int(input("Enter a Number "))
num2 = int(input("Enter 2nd Number"))
midpoint = (num1+num2) / 2
print("Midpoint of ",num1, "and",num2,"=",midpoint)

"""3.	Write a Python program to calculate the area of a triangle using the formula: area = 0.5 * base * height.

"""

# Calculte Area of triangle
base = int(input("Enter base of triangle "))
height = int(input("Enter the height of the triangle "))
area = 0.5*base*height
print("Area of Triangle is",area, "Where height = ", height, "and base =",base)

"""4.	Take three numbers as input from the user and display their product.

"""

# Product of 3 Numbers
num1 = int(input("Enter a Number "))
num2 = int(input("Enter 2nd Number "))
num3 = int(input("Enter 3rd Number "))
num = num1*num2*num3
print("Product of",num1,",",
      num2, "and", num3, "=",num)

"""5.	Take a number as input and display its square and cube.

"""

# find out squre and cube of given Number
num = int(input("Enter a Number "))
square = num*num
cube = num*num*num
print("Square of ",num, "=",square)
print("Cube of ",num, "= ",cube)

"""6.	Take two numbers as input and display their quotient and remainder.

"""

# Quotients and reminder of two number
num1 = int(input("Enter a Number "))
num2 = int(input("Enter 2nd Number "))
quotient = num1/num2
reminder = num1%num2
print("Quotient of ", num1, "And",num2, "=", quotient)
print("Reminder of ",num1, "and", num2, "=",reminder)

"""7.	Take three numbers as input and display their average.

"""

# average of three number
num1 = int(input("Enter a Number "))
num2 = int(input("Enter 2nd Number "))
num3 = int(input("Enter 3rd Number "))
avg = (num1+num2+num3) /3
print("Average of three number = ", avg)

"""8.	Write a Python program to calculate the area of a rectangle using the formula: area = length * width.

"""

# Area of rectangle
length = int(input("Enter length of rectangle "))
width = int(input("Enter width of the rectangle "))
area = length*width
print("Area of rectangle is = ", area)

"""9.	Take five numbers as input representing marks obtained and total marks.
Display the percentage.
"""

# calculate percentages
sub1 = float(input("Enter marks obtained in subject 1: "))
sub2 = float(input("Enter marks obtained in subject 2: "))
sub3 = float(input("Enter marks obtained in subject 3: "))
sub4 = float(input("Enter marks obtained in subject 4: "))
sub5 = float(input("Enter marks obtained in subject 5: "))
total_marks_possible = float(input("Enter total possible marks for all subjects: "))

marks_obtained = sub1 + sub2 + sub3 + sub4 + sub5
percentage = (marks_obtained/total_marks_possible)*100
print("Percentage = ",percentage)

"""10.	Write a Python program to swap two numbers entered by the user without using a third variable.

"""

# swap Number without 3rd variable
a = 10
b = 20

a,b=b,a
print(a)

"""11.	Take a number as input and check whether it is even or odd.

"""

# Check even or odd Number
num = int(input("Enter a Number "))
if num%2 == 0:
  print(num, "is an Even Number")
else:
  print(num, " is an odd Number")

"""12.	Write a Python program to convert temperature from Celsius to Fahrenheit using the formula: F = (C × 9/5) + 32.

"""

# Temperature to fahrenheit
c = int(input("Enter temperature "))
F = (c*9/5)+32
print("Current Fahrenheit is = ",F)

"""13.	Write a Python program to convert temperature from Fahrenheit to Celsius using the formula: C = (F - 32) × 5/9.

"""

# Fahrenheit to Temperature
F = int(input("Enter Fahrenheit "))
C = (F-32)*5/9
print("Current Temperature is = ",C)

"""14.	Take two numbers as input and find their greatest common divisor (GCD).

"""

''' Finding greatest common divisior
unporting math'''
import math
# Taking input from the user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Finding GCD
gcd = math.gcd(num1, num2)

print("GCD of ",num1,"and", num2, "is", gcd)
# other way of print
# f and {} is IMP
print(f"GDC of {num1} and {num2} is {gcd}")

"""15.	Write a Python program to calculate the simple interest using the formula: SI = (P × R × T) / 100, where P is the principal amount, R is the rate of interest, and T is the time in years.

"""

# Calculate simple interest
P = float(input("Enter principal amount "))
R = float(input("Enter rate of interest "))
T = float(input("Enter time in years "))
SI = (P*R*T)/100
print("Simple Interest = ",SI)

"""16.	Write a Python program to check whether a number is positive, negative, or zero.

"""

# check whether a number is positive, negative or Zero
num = int(input("Enter a Number : "))
if num > 0:
  print(num, "is a positive number")
elif num < 0 :
  print(num, " is a negative number")
else :
  print(num, "is a Zero")

"""17.	Write a Python program to find the largest among three numbers entered by the user.

"""

# largest amoung three number
num = int(input("Enter a Number"))
num2 = int(input("Enter 2nd Number"))
num3 = int(input("Enter 3rd Number"))

if num > num2 and num > num3:
  print(num, "is the largest number")
if num2 > num and num2 > num3:
  print(num2, "is the largest number")
else :
  print(num3, "is the largest Number2")

"""18.	Take a number as input and check whether it is a multiple of 5.

"""

#Check whether number is mutiple of 5 or not
num = float(input("Enter a number"))
if num % 5== 0:
  print(num, "is a multiple of 5")
else:
  print(f"{num} is not multiple of 5")

"""19.	Write a Python program to calculate the perimeter of a circle using the formula: perimeter = 2 * π * radius.

"""

# calculate circle parameter
import math
radius = float(input("Enter a Radius : "))
perimeter = 2 * π * radius

print ("Perimeter of circle with given ", radius, "is", perimeter)

"""20.	Write a Python program to check whether a number is divisible by both 3 and 5.

"""

num = float(input("Enter a number : "))
if num%3 == 0 and num%5 == 0:
  print(num, "is divisible by both 3 and 5")
else:
  print(f"{num} is not divisible by both 3 and 5")