# -*- coding: utf-8 -*-
"""Tuple_que.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6tjjKqHSWdM-nb_PDJpkbTxdZ5hHeEe

1.	Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you access the element 15 using positive indexing? Write a Python program to achieve this.
"""

my_tuple = (5, 10, 15, 20, 25)
my_tuple[2]

"""2.	Given a tuple my_tuple = (100, 200, 300, 400, 500), how can you access the element 300 using negative indexing? Write a Python program to achieve this.

"""

my_tuple = (100, 200, 300, 400, 500)
my_tuple[-3]

"""3.	Given a tuple my_tuple = (1, 2, 3, (4, 5, 6)), how can you access the element 6 from the nested tuple using indexing? Write a Python program to achieve this.

"""

my_tuple = (1, 2, 3, (4, 5, 6))
my_tuple[3][2]

"""4.	Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you slice it to obtain (10, 15, 20)? Write a Python program to achieve this.

"""

my_tuple = (5, 10, 15, 20, 25)
my_tuple[1:4]

"""5.	Given a tuple my_tuple = ('Python', 'Java', 'C++', 'JavaScript'), how can you access the last element without knowing its index? Write a Python program to achieve this.

"""

my_tuple = ('Python', 'Java', 'C++', 'JavaScript')
my_tuple[-1]

"""6.	Given two tuples tuple1 = (1, 2, 3) and tuple2 = (4, 5, 6), how can you concatenate them into a single tuple? Write a Python program to achieve this.

"""

tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
print(tuple1 + tuple2)

"""7.	Given a tuple my_tuple = ('x', 'y', 'z', 'a'), how can you check if the element 'y' exists in the tuple? Write a Python program to achieve this.

"""

my_tuple = ('x', 'y', 'z', 'a')
if 'y'in my_tuple:
  print("yes")
else:
  print("y is not available in  my_tuple")

"""8.	Given a tuple my_tuple = ('apple', 'banana', 'apple', 'cherry', 'apple'), how can you count the number of occurrences of 'apple'? Write a Python program to achieve this.

"""

my_tuple = ('apple', 'banana', 'apple', 'cherry', 'apple')
my_tuple.count("apple")

"""9.	Given a tuple my_tuple = (True, False, True, False), how can you find the number of True values in the tuple? Write a Python program to achieve this.

"""

my_tuple = (True, False, True, False)
my_tuple.count(True)

"""10.	Given a tuple my_tuple = ('Python', 3.8, True, (1, 2, 3)), how can you access the nested tuple (1, 2, 3)? Write a Python program to achieve this.

"""

my_tuple = ('Python', 3.8, True, (1, 2, 3))
my_tuple[3]

"""11.	Given a tuple my_tuple = (10, 20, 30), how can you convert it into a list? Write a Python program to achieve this.

"""

my_tuple = (10, 20, 30)
l = list(my_tuple)
print(l)

"""12.	Given a tuple my_tuple = (7, 14, 21, 28, 35), how can you find the smallest and largest elements? Write a Python program to achieve this.

"""

my_tuple = (7, 14, 21, 28, 35)
 print(min(my_tuple), max(my_tuple))

"""13.	Given a tuple my_tuple = (2, 4, 6, 8, 10), how can you find the sum of all elements? Write a Python program to achieve this.

"""

my_tuple = (2, 4, 6, 8, 10)
sum(my_tuple)

"""14.	Given a tuple my_tuple = ('a', 'b', 'c', 'd'), how can you reverse the order of elements? Write a Python program to achieve this.

"""

my_tuple = ('a', 'b', 'c', 'd')
my_tuple[::-1]

"""15.	Given two tuples tuple1 = (1, 2, 3) and tuple2 = (1, 2, 3), how can you check if they are equal? Write a Python program to achieve this.

"""

tuple1 = (1, 2, 3)
tuple2 = (1, 2, 3)
print(tuple1 == tuple2)

"""16.	Given a tuple my_tuple = (10, 20, 30, 40), how can you unpack its values into separate variables? Write a Python program to achieve this.

"""

my_tuple = (10, 20, 30, 40)
for i in my_tuple:
   print(i)

"""17.	Given a tuple my_tuple = (3, 6, 9, 12, 15), how can you convert it into a string? Write a Python program to achieve this.

"""

my_tuple = (3, 6, 9, 12, 15)
my_str = str(my_tuple)
print(my_set)

"""18.	Given a tuple my_tuple = (1, 2, 3, 4, 5), how can you iterate through it using a for loop? Write a Python program to achieve this.

"""

my_tuple = (1, 2, 3, 4, 5)
for i in my_tuple:
  print(i)

"""19.	Given a tuple my_tuple = (100, 200, 300, 400), how can you convert it into a dictionary with keys as index positions? Write a Python program to achieve this.

"""

my_tuple = (100, 200, 300, 400)
my_dict = dict(enumerate(my_tuple))
print(my_dict)

"""20.	Given a tuple my_tuple = (1, 2, 3, 4, 5), how can you delete the entire tuple? Write a Python program to achieve this.

"""

my_tuple = (1, 2, 3, 4, 5)
my_tuple = ()
print(my_tuple)