# -*- coding: utf-8 -*-
"""While_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lax2Gn30-xHB_PtXOp7t4EXRbMU4zkND

Q1: Write a Python program to print the sum of all even numbers between 1 and 100 using a while loop.
"""

num=0
x = 0

while x <= 100:
  x+=1
  if x % 2 == 0:
    num = num + x
print(num)

"""Q2: Write a Python program to reverse a number using a while loop.

"""

x = 1234
r = 0
while x < 0:
  x = x+1
  if x == 1234:
    r = r.append(x)
r

# Input number
num = 1234
reversed_num = 0

# Loop until the number becomes 0
while num > 0:
    # Get the last digit using modulo
    digit = num % 10
    # Append the digit to the reversed number
    reversed_num = (reversed_num * 10) + digit
    # Remove the last digit using floor division
    num = num // 10

print("Reversed Number:", reversed_num)

"""Q3: Write a Python program to find the sum of digits of a given number using a while loop.
Example:
Input: 567
"""

# Input number
num = 567
sum_of_digits = 0

# Loop until the number becomes 0
while num > 0:
    # Extract the last digit
    digit = num % 10
    # Add the digit to our total sum
    sum_of_digits += digit
    # Remove the last digit from num
    num = num // 10

print("Sum of digits:", sum_of_digits)

"""Q4: Write a Python program to find the greatest common divisor (GCD) of two numbers using a while loop.
Example:
Input: 36, 60
"""

# Input numbers
a = 36
b = 60

# Store original values for the final print statement
num1, num2 = a, b

# Loop until one of the numbers becomes 0
while b > 0:
    # Update a to b, and b to the remainder of a divided by b
    a, b = b, a % b

print(f"The GCD of {num1} and {num2} is: {a}")

"""Q5: Write a Python program to calculate the power of a number using a while loop (without using the ** operator).
Example:
Input: base = 2, exponent = 4
"""

# Input values
base = 2
exponent = 4

# Initialize result and a counter
result = 1
count = 0

# Loop until we have multiplied 'base' exponent times
while count < exponent:
    result = result * base
    count += 1

print(f"{base} raised to the power of {exponent} is: {result}")